Правки РК1
frontend-park-mail-ru/2023_2_Arkitail pull request #6
Opened 2023-10-20 10:03 UTC by uma-op

#4

2023-10-22 17:41 UTC, ZhukDmitryOlegovich requested changes
поправьте ридми

2023-10-22 17:41 UTC, ZhukDmitryOlegovich commented on source/src/js/carousel.js
> +        debounce(this.handlePrevious.bind(this), 500).bind(this)
Второй bind зачем? Вроде как не нужен

2023-10-22 17:41 UTC, ZhukDmitryOlegovich commented on source/src/js/carousel.js
> +        debounce(this.handleNext.bind(this), 500).bind(this)
надо заменить на throttle или такое поведение когда
- на первый клик - реагируем
- пока таймаут - никак на клики не реагируем
- после того как прошел таймаут - ничего не делаем
- клик после того таймаута - реагируем

2023-10-22 17:41 UTC, ZhukDmitryOlegovich commented on .gitignore
> -package.json
Чего удалили?

2023-10-22 17:41 UTC, ZhukDmitryOlegovich commented on docker/Dockerfile
> +FROM nginx:latest
зачем докер?

2023-10-25 15:04 UTC, uma-op commented on docker/Dockerfile
> +FROM nginx:latest
Для деплоя

2023-10-29 11:13 UTC, ZhukDmitryOlegovich requested changes

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/main-page.js
> +    return fetch("/api/v1/places", {
Сделайте мемоизацию - сейчас эта ручка дергается несколько раз для загрузки страницы
<img width="1215" alt="image" src="https://github.com/frontend-park-mail-ru/2023_2_Arkitail/assets/93006259/9bc765f2-f1d8-4c72-a344-651af76071b9">

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/main-page.js
> +      }
```suggestion
      places.forEach((place) => {
        this.carousel.appendSlide(place);
      });
```
а ещё лучше научить карусель принимать массив данных чтобы сделать
```suggestion
      this.carousel.appendSlides(places);
```

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/html/list-of-places.html
> +              <p>Название 6</p>
Кажется это лишние

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/carousel.js
> +}
```suggestion
const mathMod = (n, d) => ((n % d) + d) % d;
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder#:~:text=To%20obtain%20a%20modulo%20in%20JavaScript%2C%20in%20place%20of%20n%20%25%20d%2C%20use%20((n%20%25%20d)%20%2B%20d)%20%25%20d.

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/carousel.js
> +      clearTimeout(timer);
clearTimeout тут ничего не делает - timeout в момент выполнения уже сработал - можно убрать

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/carousel.js
> +    if (this.numberOfVisibleSlides == 3) {
Почему 3? Логика непонятная

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/carousel.js
> +      this.carousel.addEventListener("mouseover", this.showArrows.bind(this));
Почему так? Если просто так, то давайте сделаем показ кнопок через css и `:hover`?

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/footer.js
> +class Footer extends Page {
Футер наследует страницу? Не логично. Либо поясните что вы понимаете под страницей, либо переименуйте, либо переделайте наследования

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/handlebars.js
> +/**!
Замените на min.js https://cdn.jsdelivr.net/npm/handlebars@latest/dist/handlebars.min.js

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/footer.js
> +class Footer extends Page {
PS: аналогично для остальных - какие куски страницы наследуют страницу, какие-то не наследуют - ничего не понятно

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/header.js
> +                '/api/v1/logout',
Лучше конечно всю работу с API вынести в отдельный файл, что позволит абстрагироваться от того какой там именно запрос, настроить общую логику мемоизации, упростит добавление и обновление новых и существующих концов соответственно

Да и вообще мир станет чуточку лучше)

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/header.js
> +            authenticated: main.temporaryContext.authenticated.status,
А я тут подумал - main это кто и он где? Неужто редактор не ругается что это ничто из ниоткуда? Переделайте из глобальной сущности на импорты

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/header.js
> +                    name: 'Выйти',
Как будто бы тут также должны быть перечислены кнопки "Войти" и "Профиль"

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/list-filters.js
> +        <div data-filters>
вообще по хорошему все темплейты handlebars должны быть в отдельный файлах - и редактору будет резко проще жить и он сможет вам синтаксис подсказывать ибо сейчас это реально - просто строчки

не проблема, но на подумать

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/signup-form.js
> +      this.errorMessage.innerText = tmp.error;
надо при новом запросе на бек/при новой попытке провалидировать - поле с ошибка очищать + в него писать все ошибки что вы нашли, а не последнюю

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/src/js/signup-form.js
> +        input.style["border-width"] = "2px";
При изменение border-width форма бесяче скачет - сделайте что ширина всегда есть, а меняется только цвет (и правильнее это делать через css класс - в style залазить не корректно, потом концы сложно находить) или что высота контейнера фиксированная, но скакать не должно

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/static/css/carousel.css
>      --btn-size: 3rem;
лучше всё таки перейти на `px` потому что эти ваши `rem` везде разные + потом их сложно/невозможно с `px` состыковать

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/static/css/general.css
> +    font-family: -apple-system, BlinkMacSystemFont, Arial, sans-serif;
-apple-system надо убрать - процент эпл юзеров очень сильно меньше чем необходимое 80-90%

2023-10-29 11:13 UTC, ZhukDmitryOlegovich commented on source/static/css/list-of-places.css
> +    display: -webkit-box;
в firefox нет webkit - уточните как там будет выглядеть

2023-11-03 20:40 UTC, merged